# This is a basic workflow to help you get started with Actions

name: CI for building conan packages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: check python version
        run: |
          python --version
          pip --version

      # - name: Install Conan 2.12.0
      #   run: |
      #     pip install "conan==2.12.0"

      - name: check conan version
        run: |
          conan --version

      - name: Conan Config
        run: |
          conan config install conan2_config

    # Download the only the zip file.
      - name: Create maven conan packages
        run: |
          conan create recipes/apache-maven/binary --profile:build=Windows --profile:host=Windows

      - name: Create 7zip conan packages
        run: |
          conan create recipes/7zip/binary --profile:build=Linux --profile:host=Linux
